#!/bin/bash
# tuned for plex

inotifywait -r -m "$1" -e create -e moved_to -e modify --exclude '/[.@]' --format '%w%f' $INOTIFYWAIT_OPTS | stdbuf -oL uniq | while read -r FILE; do
	# file may yield inode/x-empty for new files
	sleep "$SETTLE_DOWN_TIME"

	# abort if the file has been modified while we were asleep
	if [ `find "$FILE" -type f -newermt "$SETTLE_DOWN_TIME seconds ago" -print -quit` ]; then
		echo "$(date) Modified: $FILE"
		continue
	fi

	# e.g. video.mp4: video/mp4
	if file --mime-type "$FILE" | egrep "directory|video|audio|empty|octet-stream"; then
		filebot -script fn:amc --action move --conflict override -r --log-file /data/amc.log --log all -non-strict --def "ignore=_unpack" "ut_label=all" "music=y" "unsorted=y" "subtitles=en" "clean=y" "deleteAfterExtract=y" "excludeList=/dev/null" "unsorted=y" "music=y" "artwork=y" "plex=$PLEXHOSTANDTOKEN" "seriesFormat={plex.root}/{az}/{plex.tail}" "animeFormat={plex.root}/{az}/{plex.tail}" "movieFormat={plex.root}/{az}/{plex.tail}" "musicFormat={plex.root}/{az}/{plex.tail}" "$@" 
		LANG=C chown -R 99:100 "${!#}"
	fi
done | gawk '{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0 }'
